openapi: 3.0.3
info:
  title: EazyShop Products APIs Definition
  description: |
    # About Us
    **EazyShop** is a open market product selling company. Any website can list our products by  using our _APIs_. Shipping & other logistics will be taken care by us. You will get an `Affiliate commision` for selling our products.
    # Categories suported
      - Mobiles
        - Apple
        - Samsung
        - OnePlus
      - Laptops
      - Televisions
      - Headphones
  termsOfService: https://eazyshop.com/terms/
  contact:
    name: API Support
    url: https://www.eazyshop.com/support
    email: support@eazyshop.com
  license:
    name: EazyShop License
    url: https://www.eazyshop.com/licenses/LICENSE-2.0.html
  version: 0.0.1
servers:
- url: https://development.eazyshop-server.com/v1
  description: Development server
tags:
- name: Categories
  description: Categories-related operations
- name: Products
  description: Products-related operations
- name: Orders
  description: Orders-related operations
paths:
  /categories:
    get:
      tags:
      - Categories
      summary: List all catgories
      description: Returns the list of categories supported by EazyShop
      operationId: categories_get
      parameters:
      - name: categoryId
        in: query
        required: false
        style: form
        explode: true
        schema:
          maximum: 1000
          minimum: 100
          type: integer
        examples:
          mobiles:
            summary: Use this example for mobiles
            value: 101
          laptops:
            value: 102
          headphones:
            value: 103
          televisions:
            value: 104
      responses:
        "200":
          description: A list of catgories
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
                x-content-type: application/json
              examples:
                all-categories-data:
                  summary: Categories example data
                  value:
                  - categoryId: 101
                    name: Mobiles
                  - categoryId: 102
                    name: Laptops
                  - categoryId: 103
                    name: Headphones
                  - categoryId: 104
                    name: Televisions
                single-category-data:
                  summary: Single category example data
                  value:
                  - categoryId: 101
                    name: Mobiles
        "500":
          description: |
            An error occured while processing the request.
            Please contact support@eazyshop.com
      x-openapi-router-controller: swagger_server.controllers.categories_controller
  /categories/{categoryId}:
    get:
      tags:
      - Categories
      summary: Return category details
      description: Returns the category details from EazyShop
      operationId: categories_category_id_get
      parameters:
      - name: categoryId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          maximum: 1000
          minimum: 100
          type: integer
        example: 102
      responses:
        "200":
          description: Return category details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        "500":
          description: |
            An error occured while processing the request.
            Please contact support@eazyshop.com
      x-openapi-router-controller: swagger_server.controllers.categories_controller
  /products:
    get:
      tags:
      - Products
      summary: List all products
      description: |
        Returns the list of products supported by EazyShop
      operationId: products_get
      parameters:
      - name: categoryId
        in: query
        required: false
        style: form
        explode: true
        schema:
          maximum: 1000
          minimum: 100
          type: integer
        example: 101
      responses:
        "200":
          description: A list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
                x-content-type: application/json
              examples:
                products-data:
                  summary: Products example data
                  value:
                  - productId: 101
                    name: Apple IPhone 13 Pro
                    price: 999
                    categoryName: Mobiles
                    quantity: 96
                  - productId: 102
                    name: Samsung S22 Ultra
                    price: 899
                    categoryName: Mobiles
                    quantity: 121
                  - productId: 103
                    name: OnePlus 10 Pro 5G
                    price: 750
                    categoryName: Mobiles
                    quantity: 67
        "500":
          description: |
            An error occured while processing the request.
            Please contact support@eazyshop.com
      x-openapi-router-controller: swagger_server.controllers.products_controller
  /products/{productId}:
    get:
      tags:
      - Products
      summary: Return product details
      description: |
        Returns the product details from  EazyShop
      operationId: products_product_id_get
      parameters:
      - name: productId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          maximum: 1000
          minimum: 100
          type: integer
        example: 101
      responses:
        "200":
          description: Return product details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        "500":
          description: |
            An error occured while processing the request.
            Please contact support@eazyshop.com
      x-openapi-router-controller: swagger_server.controllers.products_controller
  /orders:
    get:
      tags:
      - Orders
      summary: Get Order Details
      description: Get order details from EazyShop
      operationId: orders_get
      parameters:
      - name: orderId
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: integer
      responses:
        "200":
          description: Fetch Order details successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
        "500":
          description: |
            An error occured while processing the request.
            Please contact support@eazyshop.com
      x-openapi-router-controller: swagger_server.controllers.orders_controller
    put:
      tags:
      - Orders
      summary: Update Order
      description: |
        Update order details to EazyShop for processing
        and shipping
      operationId: orders_put
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/orders_body'
      responses:
        "200":
          description: Order details updated successfully
        "500":
          description: |
            An error occured while processing the request.
            Please contact support@eazyshop.com
      x-openapi-router-controller: swagger_server.controllers.orders_controller
    post:
      tags:
      - Orders
      summary: Create Order
      description: |
        Post order details to EazyShop for processing
        and shipping
      operationId: orders_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/orders_body_1'
      responses:
        "201":
          description: Order created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_201'
        "500":
          description: |
            An error occured while processing the request.
            Please contact support@eazyshop.com
      x-openapi-router-controller: swagger_server.controllers.orders_controller
    delete:
      tags:
      - Orders
      summary: Delete Order
      description: Delete order details from EazyShop
      operationId: orders_delete
      parameters:
      - name: orderId
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: integer
      responses:
        "204":
          description: Order details cancelled successfully
        "500":
          description: |
            An error occured while processing the request.
            Please contact support@eazyshop.com
      x-openapi-router-controller: swagger_server.controllers.orders_controller
components:
  schemas:
    Address:
      required:
      - addressLine
      - city
      - state
      - zipcode
      type: object
      properties:
        addressLine:
          type: string
        city:
          type: string
        state:
          type: string
          enum:
          - California
          - Texas
          - Indiana
          - New York
        zipcode:
          type: string
        isOfficeAddress:
          type: boolean
      example:
        zipcode: zipcode
        city: city
        state: California
        addressLine: addressLine
        isOfficeAddress: true
    Product:
      type: object
      properties:
        productId:
          type: integer
        name:
          type: string
        price:
          type: number
          format: float
        categoryName:
          type: string
        quantity:
          type: integer
          description: |
            ***Quantity*** represents `stock` value when this field is being sent by EazyShop.Where as in the scenarios of consumer sending this feild, it represents `number of product items` inside the order. Consumers are expected to handle the scenario of stopping the end user <u>*when the stock value is 0*</u>
        releaseDate:
          type: string
          format: date
          readOnly: true
      example:
        quantity: 1
        productId: 0
        releaseDate: 2000-01-23
        price: 6.0274563
        name: name
        categoryName: categoryName
    Category:
      type: object
      properties:
        categoryId:
          type: integer
        name:
          type: string
      example:
        name: name
        categoryId: 0
    inline_response_200:
      type: object
      properties:
        orderId:
          type: integer
        products:
          type: array
          items:
            $ref: '#/components/schemas/Product'
        address:
          $ref: '#/components/schemas/Address'
      example:
        address:
          zipcode: zipcode
          city: city
          state: California
          addressLine: addressLine
          isOfficeAddress: true
        orderId: 0
        products:
        - quantity: 1
          productId: 0
          releaseDate: 2000-01-23
          price: 6.0274563
          name: name
          categoryName: categoryName
        - quantity: 1
          productId: 0
          releaseDate: 2000-01-23
          price: 6.0274563
          name: name
          categoryName: categoryName
    orders_body:
      type: object
      properties:
        orderId:
          type: integer
        products:
          type: array
          items:
            $ref: '#/components/schemas/Product'
        address:
          $ref: '#/components/schemas/Address'
    orders_body_1:
      type: object
      properties:
        products:
          type: array
          items:
            $ref: '#/components/schemas/Product'
        address:
          $ref: '#/components/schemas/Address'
    inline_response_201:
      type: object
      properties:
        orderId:
          type: integer
      example:
        orderId: 0
  responses:
    InternalServerError:
      description: |
        An error occured while processing the request.
        Please contact support@eazyshop.com
  parameters:
    orderIdQueryParam:
      name: orderId
      in: query
      required: true
      style: form
      explode: true
      schema:
        type: integer

